blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
    toggle_publish,
)

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="blog_view"),
    path("update/<int:pk>", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>", BlogDeleteView.as_view(), name="blog_delete"),
    path("publish/<int:pk>", toggle_publish, name="toggle_publish"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Blog(models.Model):
    title = models.CharField(
        max_length=150, verbose_name="Название", help_text="Введите название"
    )
    content = models.TextField(verbose_name="Текст статьи", help_text="Введите текст")
    image = models.ImageField(
        upload_to="blog/photo",
        verbose_name="Изображение",
        help_text="Загрузите изображение",
        **NULLABLE
    )
    views_count = models.IntegerField(default=0, verbose_name="просмотры")
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    slug = models.CharField(max_length=150, verbose_name="slug", **NULLABLE)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ["title"]

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = (
        "title",
        "image",
        "content",
    )
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = (
        "title",
        "image",
        "content",
    )
    # success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:blog_view", args=[self.kwargs.get("pk")])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")


def toggle_publish(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True

    blog_item.save()

    return redirect(reverse("blog:blog_list"))

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        <div class="card-body">
                            {% csrf_token %}
                            <p>Вы точно хотите удалить статью "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отменить</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
              <img src="{{ blog.image | media_filter }}">
              <div class="card-header">
                  <h3 class="card-title">
                      {{ object.title }}
                  </h3>

              </div>
            <div class="card-body">
              <p class="card-text">{{ object.content }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                </div>
              </div>
            </div>
              <div class="card-footer">
                  Просмотры: {{ object.views_count }}
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="card">
                            {% csrf_token %}
                            {{ form.as_p }}
                    <div class="btn-group col-3" >
                        <button type="submit" class="btn btn-primary" role="button">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12 mb-5">
    <a class="btn btn-primary" href="{% url 'blog:blog_create' %}" role="button">Создать статью</a>
            <div class="col-md-4">
                {% for object in object_list %}
                <div class="card md-4box-shadow">
                    <div class="card-body">
                        <p class="card-text>">
                            {{ object | title }}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'blog:blog_view' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                <a href="{% url 'blog:blog_update' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Изменить</a>
                                <a href="{% url 'blog:blog_delete' object.pk %}" type="button"
                                  class="btn btn-sm btn-outline-secondary">Удалить</a>
                            </div>
                            {% if object.is_published %}
                                <a class="btn btn-warning" href="{% url 'blog:toggle_publish' object.pk %}">Снять с публикации</a>
                            {% else %}
                                <a class="btn btn-success" href="{% url 'blog:toggle_publish' object.pk %}">Опубликовать</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                 {% endfor %}
            </div>

    </div>
{% endblock %}